FROM centos:latest

RUN yum update -y
RUN yum install epel-release -y
RUN yum install gdb -y
RUN yum install vim -y
RUN yum install iftop -y
RUN yum install htop -y
RUN yum install iotop -y
RUN yum install cscope -y
RUN yum install tree -y
RUN yum install clang -y
RUN yum install git -y
RUN yum install nano -y

RUN dnf group install "Development Tools" -y
